name: LaTeX build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/document.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%d-%H%M%S.%N')" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheCore-fr-${{ env.NOW }}.pdf
          path: document.pdf
